kind: pipeline
type: docker
name: build docker image

trigger:
  ref:
  - refs/heads/master
  - refs/heads/**
  - refs/pull/*/head

# steps:
# - name: test
#   image: golang
#   settings:
#     repo: https://os3-318-48873.vs.sakura.ne.jp:447/sandbox/golang
#     registory: --insecure-registry https://os3-318-48873.vs.sakura.ne.jp:447
#     username: admin
#     password: OgaYu@5247
#     tags:
#       - "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}"
#       - "latest"
#     dockerfile: Dockerfile

env:
  - DOCKER_DAEMON_ARGS=--insecure-registry https://os3-318-48873.vs.sakura.ne.jp:447

script:
  - ./build.sh

  # - cd src/chat
  # - go get github.com/stretchr/gomniauth
  # - go get github.com/stretchr/gomniauth/providers/facebook
  # - go get github.com/stretchr/gomniauth/providers/github
  # - go get github.com/stretchr/gomniauth/providers/google
  # - go test
  # - go build main.go auth.go client.go room.go
