kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go test
  - go mod init
  - cd src/chat
  - go build main.go auth.go client.go room.go
  - go run main.go auth.go client.go room.go

