kind: pipeline
type: docker
name: test

trigger:
  event:
    - pull_request
    - push

steps:
- name: test
  image: golang
  commands:
  - cd src/chat
  - go get github.com/stretchr/gomniauth
  - go get github.com/stretchr/gomniauth/providers/facebook
  - go get github.com/stretchr/gomniauth/providers/github
  - go get github.com/stretchr/gomniauth/providers/google
  - go test
  - go build main.go auth.go client.go room.go
